[build]
command = "./build.sh"
publish = "."

[build.environment]
PYTHON_VERSION = "3.9.0"
PIP_VERSION = "21.1.2"

[functions]
directory = "routes"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true